repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: black
        stages: [commit]
        entry: black
        types: [python]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.274"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  
exclude: "README.md"