name: Publish to PyPI

# only trigger on tagged commits starting with "v"
on:
  push:
    tags:
      - "v*"

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1